BUNDLE_NAME = PSpotifyPrefs

PSpotifyPrefs_FILES = PSRootVC.m MiscVC.m
PSpotifyPrefs_CFLAGS = -fobjc-arc
PSpotifyPrefs_LIBRARIES += gcuniversal Kitten
PSpotifyPrefs_FRAMEWORKS = UIKit
PSpotifyPrefs_PRIVATE_FRAMEWORKS = Preferences OnBoardingKit
PSpotifyPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk